In [76]:
import pandas as pd
import matplotlib.pyplot as plt

In [77]:
df= pd.read_csv("messy_customer_sales_data.csv")

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                10200 non-null  str
 2   Gender              9174 non-null   str
 3   Age                 9249 non-null   str
 4   City                9184 non-null   str
 5   Signup_Date         10200 non-null  str
 6   Last_Purchase_Date  9188 non-null   str
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  str
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   str
dtypes: float64(2), int64(1), str(9)
memory usage: 956.4 KB

In [79]:
df.describe().round(2)

       Purchase_Amount  Feedback_Score  Phone_Number
count          9179.00         9177.00  1.020000e+04
mean          29090.13            5.48  4.979974e+09
std          208697.09            2.87  2.902593e+09
min            -500.00            1.00  9.208990e+05
25%           12295.00            3.00  2.449157e+09
50%           24330.00            5.00  4.988639e+09
75%           37130.00            8.00  7.510448e+09
max         9999999.00           10.00  9.994402e+09

In [80]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [81]:
df[df.duplicated()].shape

(15, 12)

In [82]:
df.duplicated().sum()

np.int64(15)

In [83]:
df['Customer_ID'].nunique()

9000

In [84]:
df["Customer_ID"].duplicated().sum()

np.int64(1199)

In [85]:
df['Customer_ID'].value_counts().head(10)

Customer_ID
CUST6560     2
CUST7652     2
CUST6833     2
CUST6106     2
CUST8964     2
CUST10852    2
CUST10824    2
CUST5403     2
CUST8461     2
CUST4196     2
Name: count, dtype: int64

In [86]:
df[df['Customer_ID']== 'CUST6560']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
96,CUST6560,Jeremy Wallace,NaN,NaN,DELHI,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN
3517,CUST6560,Jeremy Wallace,NaN,NaN,Delhi,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN

In [87]:
for col in df.columns:
    if df[col].nunique()<20:
        print(df[col].value_counts())
        print("-" * 50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

In [88]:
df.dropna(subset=['Customer_ID'],inplace=True)

In [89]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [90]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40.0,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [91]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [92]:
df["Age"].unique().tolist()

['52.0',
 '51.0 years',
 '62.0',
 '40.0',
 '41.0',
 nan,
 '18.0',
 '43.0 years',
 '40.0 years',
 '26.0',
 '32.0',
 '22.0',
 '59.0',
 '65.0',
 '61.0',
 '31.0',
 '54.0 years',
 '55.0',
 '69.0',
 '61.0 years',
 '24.0',
 '63.0',
 '19.0',
 '50.0',
 '56.0',
 '36.0',
 '68.0',
 '43.0',
 '38.0',
 '27.0',
 '57.0 years',
 '23.0',
 '25.0',
 '66.0',
 '28.0',
 '30.0',
 '46.0',
 '48.0',
 '20.0',
 '37.0',
 '67.0',
 '51.0',
 '35.0',
 '58.0',
 '29.0',
 'nan years',
 '39.0',
 '49.0',
 '47.0',
 '42.0',
 '44.0',
 '64.0',
 '53.0',
 '60.0',
 '59.0 years',
 '45.0',
 '21.0',
 '34.0',
 '54.0',
 '48.0 years',
 '46.0 years',
 '33.0',
 '57.0',
 '30.0 years',
 '58.0 years',
 '35.0 years',
 '34.0 years',
 '69.0 years',
 '250',
 '19.0 years',
 '27.0 years',
 '53.0 years',
 '65.0 years',
 '66.0 years',
 '44.0 years',
 '49.0 years',
 '25.0 years',
 '23.0 years',
 '62.0 years',
 '41.0 years',
 '33.0 years',
 '28.0 years',
 '22.0 years',
 '20.0 years',
 '42.0 years',
 '45.0 years',
 '3',
 '63.0 years',
 '37.0 years',
 '38.0 years',
 '55.0 years',
 '18.0 years',
 '36.0 years',
 '67.0 years',
 '29.0 years',
 '39.0 years',
 '31.0 years',
 '47.0 years',
 '52.0 years',
 '-10',
 '60.0 years',
 '24.0 years',
 '26.0 years',
 '21.0 years',
 '64.0 years',
 '50.0 years',
 '68.0 years',
 '32.0 years',
 '56.0 years']

In [93]:
df["Age"]= df["Age"].str.replace("years","",regex=False)

In [94]:
df["Age"]

0         52.0
1        51.0
2         62.0
3         40.0
4         41.0
         ...
10194     40.0
10195    35.0
10197     25.0
10198     55.0
10199     34.0
Name: Age, Length: 9177, dtype: str

In [95]:
import numpy as np
df["Age"]=df["Age"].replace("nan",np.nan)

In [96]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [97]:
df["Age"] = pd.to_numeric(df["Age"],errors= 'coerce')

In [98]:
df.loc[(df["Age"]<0) | (df["Age"]>100),"Age"]

470     250.0
932     250.0
2702    -10.0
5279    250.0
5949    250.0
6085    250.0
6615    250.0
7720    -10.0
7752    250.0
8337    -10.0
Name: Age, dtype: float64

In [99]:
df.loc[(df["Age"]<0) | (df["Age"]>100),"Age"]=np.nan

In [100]:
df.loc[df["Age"]==3,"Age"]=np.nan

In [101]:
df["Age"]== df["Age"].astype("Int64")

0        True
1        True
2        True
3        True
4        True
         ...
10194    True
10195    True
10197    True
10198    True
10199    True
Name: Age, Length: 9177, dtype: boolean

In [102]:
df["Age"].isna().sum()

np.int64(931)

In [103]:
df["Age"].isna().mean()*100

np.float64(10.144927536231885)

In [104]:
df["Age"].describe()

count    8246.000000
mean       43.501334
std        14.940641
min        18.000000
25%        31.000000
50%        43.000000
75%        56.000000
max        69.000000
Name: Age, dtype: float64

In [105]:
df["Age"].skew()

np.float64(0.0030907503737534602)

In [106]:
df["Age"]= df["Age"].fillna(df["Age"].median())

In [107]:
df["Age"].isnull().sum()

np.int64(0)

In [108]:
df["Purchase_Amount"].isnull().sum()

np.int64(927)

In [109]:
df["Purchase_Amount"].describe().round(2)

count       8250.00
mean       29536.98
std       220077.78
min         -500.00
25%        12278.00
50%        24268.00
75%        37109.00
max      9999999.00
Name: Purchase_Amount, dtype: float64

In [110]:
(df["Purchase_Amount"]==9999999.00).sum()

np.int64(4)

In [111]:
df.loc[df["Purchase_Amount"] != 9999999.00, "Purchase_Amount"].max()

np.float64(49992.0)

In [112]:
df.loc[df["Purchase_Amount"] < 0, "Purchase_Amount"]

28     -500.0
68     -500.0
722    -500.0
1630   -500.0
Name: Purchase_Amount, dtype: float64

In [113]:
df["Purchase_Amount"]= df["Purchase_Amount"].replace([9999999.00,-500.0],np.nan)

In [114]:
df["Purchase_Amount"]= df["Purchase_Amount"].fillna(df["Purchase_Amount"].median())

In [115]:
df["Purchase_Amount"].isna().sum()

np.int64(0)

In [116]:
df["Purchase_Amount"].describe()

count     9177.000000
mean     24667.395881
std      13604.171709
min          0.000000
25%      13886.000000
50%      24268.000000
75%      35623.000000
max      49992.000000
Name: Purchase_Amount, dtype: float64

In [117]:
df["Feedback_Score"].isnull().sum()

np.int64(905)

In [118]:
df["Feedback_Score"].describe()

count    8272.000000
mean        5.482229
std         2.863463
min         1.000000
25%         3.000000
50%         6.000000
75%         8.000000
max        10.000000
Name: Feedback_Score, dtype: float64

In [119]:
df["Feedback_Score"].value_counts(dropna=False).sort_index()

Feedback_Score
1.0     816
2.0     858
3.0     820
4.0     847
5.0     794
6.0     830
7.0     851
8.0     842
9.0     814
10.0    800
NaN     905
Name: count, dtype: int64

In [120]:
df["Feedback_Score"].mode()

0    2.0
Name: Feedback_Score, dtype: float64

In [147]:
df["Feedback_Score"]= df["Feedback_Score"].fillna(df["Feedback_Score"].mode()[0])

In [148]:
df["Feedback_Score"].isnull().sum()

np.int64(0)

In [149]:
df["Feedback_Score"].describe()

count    9177.000000
mean        5.138825
std         2.910110
min         1.000000
25%         2.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Feedback_Score, dtype: float64

In [150]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [151]:
df["Gender"].value_counts(dropna=False)

Gender
Male      5074
Female    4103
Name: count, dtype: int64

In [152]:
df["Gender"]= df["Gender"].str.lower()

In [153]:
df["Gender"].nunique()

2

In [154]:
df["Gender"] = df["Gender"].str.strip()

In [155]:
df["Gender"].value_counts()

Gender
male      5074
female    4103
Name: count, dtype: int64

In [156]:
df["Gender"]= df["Gender"].replace({
    "m":"Male",
    "male":"Male",
    "f": "Female",
    "female":"Female"
})

In [157]:
df["Gender"].value_counts(dropna=False)

Gender
Male      5074
Female    4103
Name: count, dtype: int64

In [158]:
df["Gender"].mode()[0]

'Male'

In [159]:
df["Gender"]= df["Gender"].fillna(df["Gender"].mode()[0])

In [160]:
df["Gender"].isnull().sum()

np.int64(0)

In [161]:
df["Gender"].value_counts()

Gender
Male      5074
Female    4103
Name: count, dtype: int64

In [171]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                    0
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [163]:
df["City"].value_counts(dropna="False")

City
Mumbai        1386
Kolkata       1385
Chennai       1380
Delhi         1376
Bangalore     1367
Hyderabad     1365
Name: count, dtype: int64

In [164]:
df["City"].nunique()

6

In [165]:
df["City"] = df["City"].str.title()

In [166]:
df["City"].nunique()

6

In [167]:
df["City"].value_counts(dropna=False)

City
 Mumbai        1386
 Kolkata       1385
 Chennai       1380
 Delhi         1376
 Bangalore     1367
 Hyderabad     1365
NaN             918
Name: count, dtype: int64

In [170]:
df["City"] = df["City"].fillna("unknown")

In [173]:
df["Country"].value_counts(dropna=False)

Country
India    6426
IND       704
InDia     694
india     689
NaN       664
Name: count, dtype: int64

In [174]:
df["Country"] = df["Country"].str.strip()

In [175]:
df["Country"] = df["Country"].str.title()

In [179]:
df["Country"] = df["Country"].replace("Ind", "India")

In [181]:
df["Country"] = df["Country"].fillna('India')

In [182]:
df["Country"].value_counts(dropna=False)

Country
India    9177
Name: count, dtype: int64

In [185]:
df["Last_Purchase_Date"].isnull().sum()

np.int64(914)

In [187]:
df["Last_Purchase_Date"].head(20)

0     2025-05-17
1     2025-07-22
2     2024-12-08
3     2025-10-02
4     2024-12-15
5     2025-06-09
6     2025-04-25
7     2025-04-25
8     2024-10-30
9     2024-10-15
10    2025-01-20
11    2025-07-09
12    2025-06-29
13    2025-04-24
14    2025-09-03
15    2025-03-11
16    2025-02-24
17    2025-09-30
18    2024-12-24
20    2025-07-18
Name: Last_Purchase_Date, dtype: str

In [188]:
df["Last_Purchase_Date"].value_counts(dropna=False).head(20)

Last_Purchase_Date
NaN           914
2025-06-17     39
2024-10-17     35
2024-12-15     34
2025-02-12     34
2024-11-01     33
2025-07-12     33
2024-11-16     33
2025-06-27     32
2025-09-06     32
2025-06-18     32
2024-10-08     32
2024-10-28     32
2025-07-04     32
2024-12-25     31
2025-09-12     31
2025-06-30     31
2025-09-26     31
2025-02-27     30
2025-03-02     30
Name: count, dtype: int64

In [189]:
df["Last_Purchase_Date"].head(10)

0    2025-05-17
1    2025-07-22
2    2024-12-08
3    2025-10-02
4    2024-12-15
5    2025-06-09
6    2025-04-25
7    2025-04-25
8    2024-10-30
9    2024-10-15
Name: Last_Purchase_Date, dtype: str

In [190]:
df["Last_Purchase_Date"] = pd.to_datetime(
    df["Last_Purchase_Date"],
    errors="coerce"
)

In [191]:
df["Last_Purchase_Date"].dtype

dtype('<M8[us]')

In [194]:
df["Last_Purchase_Date"].min()

Timestamp('2024-10-08 00:00:00')

In [195]:
df["Last_Purchase_Date"].max()

Timestamp('2025-10-08 00:00:00')

In [219]:
df["Last_Purchase_Date"]=df["Last_Purchase_Date"].ffill()

In [198]:
df["Signup_Date"] = pd.to_datetime(
    df["Signup_Date"],
    errors="coerce"
)

In [210]:
df["Signup_Date"].dtype

dtype('<M8[us]')

In [220]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    1
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [209]:
df.duplicated().sum()

np.int64(150)

In [211]:
df.info()

<class 'pandas.DataFrame'>
Index: 9177 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                9177 non-null   str
 2   Gender              9177 non-null   str
 3   Age                 9177 non-null   float64
 4   City                9177 non-null   str
 5   Signup_Date         9177 non-null   datetime64[us]
 6   Last_Purchase_Date  9176 non-null   datetime64[us]
 7   Purchase_Amount     9177 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               9177 non-null   str
 10  Phone_Number        9177 non-null   int64
 11  Country             9177 non-null   str
dtypes: datetime64[us](2), float64(3), int64(1), str(6)
memory usage: 932.0 KB

In [213]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [217]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    1
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [218]:
df.info()

<class 'pandas.DataFrame'>
Index: 9027 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9027 non-null   str
 1   Name                9027 non-null   str
 2   Gender              9027 non-null   str
 3   Age                 9027 non-null   float64
 4   City                9027 non-null   str
 5   Signup_Date         9027 non-null   datetime64[us]
 6   Last_Purchase_Date  9026 non-null   datetime64[us]
 7   Purchase_Amount     9027 non-null   float64
 8   Feedback_Score      9027 non-null   float64
 9   Email               9027 non-null   str
 10  Phone_Number        9027 non-null   int64
 11  Country             9027 non-null   str
dtypes: datetime64[us](2), float64(3), int64(1), str(6)
memory usage: 916.8 KB

In [ ]:
df.to_csv("cleaned_customer_sales_data.csv", index=False)